//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeliosGlamour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int Id { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> FK_Local { get; set; }
        public Nullable<int> FK_Empleado { get; set; }
        public Nullable<int> FK_Servicio { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Local Local { get; set; }
        public virtual Servicio_Local Servicio_Local { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
