//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeliosGlamour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int Id { get; set; }
        public Nullable<int> FK_Usuario { get; set; }
        public Nullable<int> FK_Local { get; set; }
        public Nullable<int> FK_Empleado { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> FK_Estatus { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> FK_Servicio { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public string Comentario { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual Local Local { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
