//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeliosGlamour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruccion
    {
        public int Id { get; set; }
        public string Instruccion1 { get; set; }
        public Nullable<int> FK_Local { get; set; }
        public Nullable<int> FK_Servicio { get; set; }
    }
}
