//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeliosGlamour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion_Local
    {
        public int Id { get; set; }
        public Nullable<int> FK_Promocion { get; set; }
        public Nullable<int> FK_Local { get; set; }
    }
}
